#!/usr/bin/env python3
"""
DELTA-V Autocoder
=================
Reads topology.yaml and generates:
  1. dictionary.json           — Ground Data System dictionary
  2. src/Types.hpp             — DO-178C compliant C++ packet definitions
  3. src/TopologyManager.hpp   — Auto-wires all C++ components automatically
"""
import yaml
import json
import os
import sys

YAML_FILE  = "topology.yaml"
DICT_FILE  = "dictionary.json"
TYPES_FILE = "src/Types.hpp"
TOPO_FILE  = "src/TopologyManager.hpp"

CCSDS_SYNC_WORD = 0x1ACFFC1D

def build_ground_dictionary(topology: dict) -> None:
    name    = topology["system"]["name"]
    version = topology["system"]["version"]
    print(f"[Autocoder] Building GDS dictionary for {name} v{version}...")

    gds_dict = {
        "_meta": {
            "system":   name,
            "version":  version,
            "sync_word": hex(CCSDS_SYNC_WORD),
            "apids": {
                "telemetry": 10,
                "event":     20,
                "command":   30
            }
        },
        "components": {},
        "commands":   {},
        "params":     {}
    }

    for comp in topology.get("components", []):
        gds_dict["components"][str(comp["id"])] = {
            "name": comp["name"],
            "type": comp.get("type", "Passive")
        }

    for cmd in topology.get("commands", []):
        gds_dict["commands"][cmd["name"]] = {
            "target_id":   cmd["target_id"],
            "opcode":      cmd["opcode"],
            "description": cmd.get("description", ""),
            "apid":        30
        }

    with open(DICT_FILE, "w") as f:
        json.dump(gds_dict, f, indent=4)

    print(f"[Autocoder] dictionary.json: {len(gds_dict['components'])} components, {len(gds_dict['commands'])} commands.")

def build_cpp_types() -> None:
    print(f"[Autocoder] Generating {TYPES_FILE}...")
    os.makedirs(os.path.dirname(TYPES_FILE), exist_ok=True)

    cpp = r"""#pragma once
// =============================================================================
// Types.hpp — DELTA-V Wire Protocol & Packet Definitions
// =============================================================================
// ⚠️  AUTOGENERATED FILE: DO NOT MODIFY BY HAND. RUN autocoder.py  ⚠️

#include <cstdint>
#include <cstring>

namespace deltav {

#pragma pack(push, 1)

struct CcsdsHeader {
    uint32_t sync_word;    
    uint16_t apid;         
    uint16_t seq_count;    
    uint16_t payload_len;  
};
static_assert(sizeof(CcsdsHeader) == 10, "CcsdsHeader must be 10 bytes");

struct CcsdsCrc {
    uint16_t crc16;        
};

struct TelemetryPacket {
    uint32_t timestamp_ms;   
    uint32_t component_id;   
    float    data_payload;   
};
static_assert(sizeof(TelemetryPacket) == 12, "TelemetryPacket must be 12 bytes");

struct CommandPacket {
    uint32_t target_id;    
    uint32_t opcode;       
    float    argument;     
};
static_assert(sizeof(CommandPacket) == 12, "CommandPacket must be 12 bytes");

struct EventPacket {
    uint32_t severity;     
    uint32_t source_id;    
    char     message[28];  

    static EventPacket create(uint32_t sev, uint32_t src, const char* msg) {
        EventPacket p{};
        p.severity  = sev;
        p.source_id = src;
        std::strncpy(p.message, msg, sizeof(p.message) - 1);
        p.message[sizeof(p.message) - 1] = '\0';
        return p;
    }
};
static_assert(sizeof(EventPacket) == 36, "EventPacket must be 36 bytes");

#pragma pack(pop)

namespace Severity {
    constexpr uint32_t INFO     = 1;
    constexpr uint32_t WARNING  = 2;
    constexpr uint32_t CRITICAL = 3;
}

namespace Apid {
    constexpr uint16_t TELEMETRY = 10;
    constexpr uint16_t EVENT     = 20;
    constexpr uint16_t COMMAND   = 30;
}

constexpr uint32_t CCSDS_SYNC_WORD = 0x1ACFFC1Du;

} // namespace deltav
"""
    with open(TYPES_FILE, "w") as f:
        f.write(cpp)


def build_topology_manager(topology: dict) -> None:
    print(f"[Autocoder] Generating {TOPO_FILE}...")
    
    comps = topology.get("components", [])
    commands = topology.get("commands", [])
    custom_wires = topology.get("custom_wiring", [])

    includes, instances, register_all, register_fdir = [], [], [], []
    cmd_routes, cmd_wiring, telem_wiring = [], [], []
    event_staging, event_wiring = [], []

    # Hardcoded System Hub Links
    cmd_wiring.append("        radio.command_out.connect(&cmd_hub.cmd_input);")
    telem_wiring.append("        telem_hub.registerListener(&radio.telem_in);")
    telem_wiring.append("        telem_hub.registerListener(&recorder.telemetry_in);")
    event_wiring.append("        event_hub.registerListener(&radio.event_in);")
    event_wiring.append("        event_hub.registerListener(&recorder.event_in);")

    for comp in comps:
        cls = comp.get("class", comp["name"] + "Component")
        inst = comp.get("instance", comp["name"].lower())
        cid = comp["id"]

        inc = f'#include "{cls}.hpp"'
        if inc not in includes:
            includes.append(inc)

        instances.append(f'    {cls:<20} {inst:<15}{{"{comp["name"]}", {cid}}};')
        register_all.append(f'        sys.registerComponent(&{inst});')

        # FDIR Self-Monitoring (everyone except the passive data sinks)
        if inst not in ["telem_hub", "recorder"]:
            register_fdir.append(f'        watchdog.registerSubsystem(&{inst});')

        # Event Hub routing
        if inst in ["watchdog", "cmd_hub", "event_hub", "radio", "recorder", "telem_hub"]:
            if inst == "watchdog":
                event_staging.append(f'    InputPort<EventPacket> e_watchdog;')
                event_wiring.append(f'        watchdog.event_out.connect(&e_watchdog);')
                event_wiring.append(f'        event_hub.registerEventSource(&e_watchdog);')
            elif inst == "cmd_hub":
                event_staging.append(f'    InputPort<EventPacket> e_cmd_hub;')
                event_wiring.append(f'        cmd_hub.ack_out.connect(&e_cmd_hub);')
                event_wiring.append(f'        event_hub.registerEventSource(&e_cmd_hub);')
        else:
            # Automatic App Wiring (Telemetry, Events, Commands)
            telem_wiring.append(f'        telem_hub.connectInput({inst}.telemetry_out);')
            event_staging.append(f'    InputPort<EventPacket> e_{inst};')
            event_wiring.append(f'        {inst}.event_out.connect(&e_{inst});')
            event_wiring.append(f'        event_hub.registerEventSource(&e_{inst});')

            comp_cmds = [c for c in commands if c["target_id"] == cid]
            if comp_cmds:
                cmd_routes.append(f'    OutputPort<CommandPacket> {inst}_cmd_route;')
                cmd_wiring.append(f'        {inst}_cmd_route.connect(&{inst}.cmd_in);')
                cmd_wiring.append(f'        cmd_hub.registerRoute({cid}, &{inst}_cmd_route);')

    cpp_template = """#pragma once
// =============================================================================
// TopologyManager.hpp — AUTOGENERATED BY DELTA-V AUTOCODER
// =============================================================================

#include "Port.hpp"
#include "Types.hpp"
#include "Scheduler.hpp"
#include <iostream>
{includes_str}

namespace deltav {{

class TopologyManager {{
public:
{instances_str}

    void wire() {{
        wireTelemetry();
        wireCommands();
        wireEvents();
        wireCustom();
        std::cout << "[Topology] All ports connected.\\n";
    }}

    void registerAll(Scheduler& sys) {{
{register_all_str}
    }}

    void registerFdir() {{
{register_fdir_str}
    }}

    bool verify() {{
        bool ok = true;
        auto check = [&](bool condition, const char* name) {{
            if (!condition) {{
                std::cerr << "[Topology] UNCONNECTED/INVALID: " << name << "\\n";
                ok = false;
            }}
        }};

        check(radio.command_out.isConnected(),           "radio.command_out -> cmd_hub");
        check(cmd_hub.ack_out.isConnected(),             "cmd_hub.ack_out -> event_hub");
        check(event_hub.getSourceCount()   >= 4, "event_hub: need >=4 sources");
        check(event_hub.getListenerCount() >= 2, "event_hub: need >=2 listeners");

        if (!ok) std::cerr << "[Topology] FATAL: wiring incomplete.\\n";
        return ok;
    }}

private:
{cmd_routes_str}

{event_staging_str}

    void wireTelemetry() {{
{telem_wiring_str}
    }}

    void wireCommands() {{
{cmd_wiring_str}
    }}

    void wireEvents() {{
{event_wiring_str}
    }}

    void wireCustom() {{
{custom_wiring_str}
    }}
}};

}} // namespace deltav
"""

    out_content = cpp_template.format(
        includes_str="\n".join(includes),
        instances_str="\n".join(instances),
        register_all_str="\n".join(register_all),
        register_fdir_str="\n".join(register_fdir),
        cmd_routes_str="\n".join(cmd_routes),
        event_staging_str="\n".join(event_staging),
        telem_wiring_str="\n".join(telem_wiring),
        cmd_wiring_str="\n".join(cmd_wiring),
        event_wiring_str="\n".join(event_wiring),
        custom_wiring_str="\n".join([f"        {w}" for w in custom_wires])
    )

    with open(TOPO_FILE, "w") as f:
        f.write(out_content)

def validate_topology(topology: dict) -> bool:
    errors = []
    seen_ids = {}
    for comp in topology.get("components", []):
        cid = comp["id"]
        if cid in seen_ids:
            errors.append(f"Duplicate component ID {cid}: '{comp['name']}' and '{seen_ids[cid]}'")
        seen_ids[cid] = comp["name"]

    valid_ids = set(seen_ids.keys())
    for cmd in topology.get("commands", []):
        if cmd["target_id"] not in valid_ids:
            errors.append(f"Command '{cmd['name']}' targets unknown ID {cmd['target_id']}")

    if errors:
        for e in errors:
            print(f"[Autocoder] ERROR: {e}", file=sys.stderr)
        return False
    return True

def main() -> None:
    if not os.path.exists(YAML_FILE):
        print(f"[Autocoder] FATAL: {YAML_FILE} not found.", file=sys.stderr)
        sys.exit(1)

    with open(YAML_FILE) as f:
        topology = yaml.safe_load(f)

    print(f"[Autocoder] Validating topology...")
    if not validate_topology(topology):
        print("[Autocoder] Topology validation FAILED. Aborting.", file=sys.stderr)
        sys.exit(1)
    print("[Autocoder] Topology OK.")

    build_ground_dictionary(topology)
    build_cpp_types()
    build_topology_manager(topology)
    print("[Autocoder] Done.")

if __name__ == "__main__":
    main()