#!/usr/bin/env python3
"""
DELTA-V Autocoder
=================
Reads topology.yaml and generates:
  1. dictionary.json  — Ground Data System command/telemetry dictionary
  2. src/Types.hpp    — DO-178C compliant C++ packet definitions (autogenerated)

The CCSDS sync word is now 0x1ACFFC1D (standard) replacing the old 0xDEADBEEF.
"""
import yaml
import json
import os
import sys

YAML_FILE  = "topology.yaml"
DICT_FILE  = "dictionary.json"
TYPES_FILE = "src/Types.hpp"

# ---------------------------------------------------------------------------
# CCSDS-compliant sync word (standard transfer frame sync marker)
# This must match the value in Types.hpp: CCSDS_SYNC_WORD = 0x1ACFFC1D
# ---------------------------------------------------------------------------
CCSDS_SYNC_WORD = 0x1ACFFC1D

def build_ground_dictionary(topology: dict) -> None:
    name    = topology["system"]["name"]
    version = topology["system"]["version"]
    print(f"[Autocoder] Building GDS dictionary for {name} v{version}...")

    gds_dict = {
        "_meta": {
            "system":   name,
            "version":  version,
            "sync_word": hex(CCSDS_SYNC_WORD),
            "apids": {
                "telemetry": 10,
                "event":     20,
                "command":   30
            }
        },
        "components": {},
        "commands":   {},
        "params":     {}
    }

    for comp in topology.get("components", []):
        gds_dict["components"][str(comp["id"])] = {
            "name": comp["name"],
            "type": comp.get("type", "Passive")
        }

    for cmd in topology.get("commands", []):
        gds_dict["commands"][cmd["name"]] = {
            "target_id":   cmd["target_id"],
            "opcode":      cmd["opcode"],
            "description": cmd.get("description", ""),
            "apid":        30
        }

    for param in topology.get("params", []):
        gds_dict["params"][param["name"]] = {
            "id":          param["id"],
            "default":     param.get("default", 0.0),
            "description": param.get("description", "")
        }

    with open(DICT_FILE, "w") as f:
        json.dump(gds_dict, f, indent=4)

    cmd_count   = len(gds_dict["commands"])
    comp_count  = len(gds_dict["components"])
    print(f"[Autocoder] dictionary.json: {comp_count} components, {cmd_count} commands.")


def build_cpp_types() -> None:
    print(f"[Autocoder] Generating {TYPES_FILE}...")
    os.makedirs(os.path.dirname(TYPES_FILE), exist_ok=True)

    cpp = r"""#pragma once
// =============================================================================
// Types.hpp — DELTA-V Wire Protocol & Packet Definitions
// =============================================================================
// ⚠️  AUTOGENERATED FILE: DO NOT MODIFY BY HAND. RUN autocoder.py  ⚠️
//
// DO-178C: #pragma pack(push,1) enforces zero compiler padding.
// All sizeof() assertions are verified at compile time via static_assert.
//
// CCSDS compliance:
//   Sync word 0x1ACFFC1D is the CCSDS standard transfer frame sync marker.
//   APID 10 = Telemetry, APID 20 = Events, APID 30 = Commands (mission-local).
// =============================================================================
#include <cstdint>
#include <cstring>

namespace deltav {

#pragma pack(push, 1)

struct CcsdsHeader {
    uint32_t sync_word;    // 0x1ACFFC1D — CCSDS standard sync marker
    uint16_t apid;         // Application Process ID
    uint16_t seq_count;    // Sequence counter
    uint16_t payload_len;  // Payload byte length (excludes header and CRC)
};
static_assert(sizeof(CcsdsHeader) == 10, "CcsdsHeader must be 10 bytes");

struct CcsdsCrc {
    uint16_t crc16;        // CRC-16/CCITT appended after payload
};

struct TelemetryPacket {
    uint32_t timestamp_ms;   // Mission Elapsed Time (TimeService::getMET())
    uint32_t component_id;   // Matches Component::getId()
    float    data_payload;   // Engineering-unit value
};
static_assert(sizeof(TelemetryPacket) == 12, "TelemetryPacket must be 12 bytes");

struct CommandPacket {
    uint32_t target_id;    // Destination component ID
    uint32_t opcode;       // Mission-defined operation code
    float    argument;     // Optional scalar argument
};
static_assert(sizeof(CommandPacket) == 12, "CommandPacket must be 12 bytes");

struct EventPacket {
    uint32_t severity;     // 1=INFO, 2=WARNING, 3=CRITICAL
    uint32_t source_id;    // Component ID that raised the event
    char     message[28];  // Null-terminated ASCII message

    static EventPacket create(uint32_t sev, uint32_t src, const char* msg) {
        EventPacket p{};
        p.severity  = sev;
        p.source_id = src;
        std::strncpy(p.message, msg, sizeof(p.message) - 1);
        p.message[sizeof(p.message) - 1] = '\0';
        return p;
    }
};
static_assert(sizeof(EventPacket) == 36, "EventPacket must be 36 bytes");

#pragma pack(pop)

namespace Severity {
    constexpr uint32_t INFO     = 1;
    constexpr uint32_t WARNING  = 2;
    constexpr uint32_t CRITICAL = 3;
}

namespace Apid {
    constexpr uint16_t TELEMETRY = 10;
    constexpr uint16_t EVENT     = 20;
    constexpr uint16_t COMMAND   = 30;
}

constexpr uint32_t CCSDS_SYNC_WORD = 0x1ACFFC1Du;

} // namespace deltav
"""
    with open(TYPES_FILE, "w") as f:
        f.write(cpp)
    print(f"[Autocoder] {TYPES_FILE} written.")


def validate_topology(topology: dict) -> bool:
    """Catch common topology errors before code generation."""
    errors = []

    # Check for duplicate component IDs
    seen_ids = {}
    for comp in topology.get("components", []):
        cid = comp["id"]
        if cid in seen_ids:
            errors.append(f"Duplicate component ID {cid}: '{comp['name']}' and '{seen_ids[cid]}'")
        seen_ids[cid] = comp["name"]

    # Check command target IDs reference valid components
    valid_ids = set(seen_ids.keys())
    for cmd in topology.get("commands", []):
        if cmd["target_id"] not in valid_ids:
            errors.append(f"Command '{cmd['name']}' targets unknown ID {cmd['target_id']}")

    if errors:
        for e in errors:
            print(f"[Autocoder] ERROR: {e}", file=sys.stderr)
        return False
    return True


def main() -> None:
    if not os.path.exists(YAML_FILE):
        print(f"[Autocoder] FATAL: {YAML_FILE} not found.", file=sys.stderr)
        sys.exit(1)

    with open(YAML_FILE) as f:
        topology = yaml.safe_load(f)

    print(f"[Autocoder] Validating topology...")
    if not validate_topology(topology):
        print("[Autocoder] Topology validation FAILED. Aborting.", file=sys.stderr)
        sys.exit(1)
    print("[Autocoder] Topology OK.")

    build_ground_dictionary(topology)
    build_cpp_types()
    print("[Autocoder] Done.")


if __name__ == "__main__":
    main()