import yaml
import json
import os

YAML_FILE = "topology.yaml"
DICT_FILE = "dictionary.json"
TYPES_FILE = "src/Types.hpp"

def build_ground_dictionary(topology):
    print(f"[Autocoder] Building Ground Dictionary for {topology['system']['name']}...")
    
    gds_dict = {
        "components": {},
        "commands": {}
    }
    
    for comp in topology.get("components", []):
        gds_dict["components"][str(comp["id"])] = comp["name"]
        
    for cmd in topology.get("commands", []):
        gds_dict["commands"][cmd["name"]] = {
            "target_id": cmd["target_id"],
            "opcode": cmd["opcode"]
        }
        
    with open(DICT_FILE, "w") as f:
        json.dump(gds_dict, f, indent=4)
        
    print(f"[Autocoder] Success! {DICT_FILE} generated.")

def build_cpp_types():
    print(f"[Autocoder] Generating DO-178C compliant C++ types ({TYPES_FILE})...")
    
    os.makedirs(os.path.dirname(TYPES_FILE), exist_ok=True)
    
    cpp_code = """#pragma once
#include <cstdint>
#include <cstring>

namespace deltav {

// NASA-GRADE: Enforce strict DO-178C memory layout (Zero compiler padding allowed)
// -----------------------------------------------------------------
// ⚠️ AUTOGENERATED FILE: DO NOT MODIFY BY HAND. RUN autocoder.py ⚠️
// -----------------------------------------------------------------
#pragma pack(push, 1)

// 🚀 UPGRADE: Aerospace Packet Framing Header (10 Bytes)
struct CcsdsHeader {
    uint32_t sync_word;
    uint16_t apid;
    uint16_t seq_count;
    uint16_t payload_len;
};

struct TelemetryPacket {
    uint32_t timestamp_ms;
    uint32_t component_id;
    float data_payload;
};

struct CommandPacket {
    uint32_t target_id;
    uint32_t opcode;
    float argument;
};

struct EventPacket {
    uint32_t severity;
    char message[32];

    static EventPacket create(uint32_t sev, const char* msg) {
        EventPacket p;
        p.severity = sev;
        std::strncpy(p.message, msg, 31);
        p.message[31] = '\\0';
        return p;
    }
};

#pragma pack(pop)

} // namespace deltav
"""
    with open(TYPES_FILE, "w") as f:
        f.write(cpp_code)
        
    print(f"[Autocoder] Success! {TYPES_FILE} generated.")

def main():
    if not os.path.exists(YAML_FILE):
        print(f"[FATAL] Could not find {YAML_FILE}. Aborting.")
        return
        
    with open(YAML_FILE, "r") as f:
        topology = yaml.safe_load(f)
        
    build_ground_dictionary(topology)
    build_cpp_types()
    
if __name__ == "__main__":
    main()