#pragma once
// ============================================================================
// TopologyManager.hpp — AUTOGENERATED BY DELTA-V AUTOCODER v4.0
// ============================================================================
// DO NOT EDIT BY HAND.  Regenerate: python3 tools/autocoder.py
// ============================================================================
#include "Port.hpp"
#include "Types.hpp"
#include "RateGroupExecutive.hpp"
#include "TmrStore.hpp"
#include "Hal.hpp"
#include <cstdio>
#include "WatchdogComponent.hpp"
#include "TelemHub.hpp"
#include "CommandHub.hpp"
#include "EventHub.hpp"
#include "TelemetryBridge.hpp"
#include "LoggerComponent.hpp"
#include "SensorComponent.hpp"
#include "PowerComponent.hpp"
#include "ImuComponent.hpp"
#if defined(ESP_PLATFORM)
#include "esp_log.h"
#endif

namespace deltav {

#if defined(ESP_PLATFORM)
static constexpr const char* TOPOLOGY_LOG_TAG = "Topology";
#endif

struct TopologyManager {
private:
    hal::I2cBus* i2c_{nullptr};

public:
    explicit TopologyManager(hal::I2cBus& i2c) : i2c_(&i2c) {}

    // ── Component instances ───────────────────────────────────────────────
    WatchdogComponent      watchdog        {"Supervisor", 1};
    TelemHub               telem_hub       {"TelemHub", 10};
    CommandHub             cmd_hub         {"CmdHub", 11};
    EventHub               event_hub       {"EventHub", 12};
    TelemetryBridge        radio           {"RadioLink", 20};
    LoggerComponent        recorder        {"BlackBox", 30};
    SensorComponent        star_tracker    {"StarTracker", 100};
    PowerComponent         battery         {"BatterySystem", 200};
    ImuComponent           imu_unit        {"IMU_01", 300, *i2c_};

    // TMR-protected parameters (auto-generated)
    TmrStore<float>  tmr_safe_mode_battery_pct{ 5.0f };
    TmrStore<float>  tmr_degraded_battery_pct{ 15.0f };
    TmrStore<float>  tmr_emergency_battery_pct{ 2.0f };

    // ── Lifecycle ─────────────────────────────────────────────────────────

    auto wire() -> void {
        wireTelemetry();
        wireCommands();
        wireEvents();
        wireCustom();
#if defined(ESP_PLATFORM)
        ESP_LOGI(TOPOLOGY_LOG_TAG, "All ports connected.");
#else
        std::printf("[Topology] All ports connected.\n");
#endif
    }

    auto registerAll(RateGroupExecutive& rge) -> void {
        // ── FAST tier (10 Hz) ─────────────────────────
        rge.registerFast(&star_tracker);
        rge.registerFast(&imu_unit);
        // ── NORM tier  (1 Hz) ─────────────────────────
        rge.registerNorm(&watchdog);
        rge.registerNorm(&telem_hub);
        rge.registerNorm(&cmd_hub);
        rge.registerNorm(&event_hub);
        rge.registerNorm(&recorder);
        rge.registerNorm(&battery);
        // ── Active (own thread) ────────────────────────
        rge.registerComponent(&radio);

    }

    auto registerFdir() -> void {
        watchdog.registerSubsystem(&watchdog);
        watchdog.registerSubsystem(&cmd_hub);
        watchdog.registerSubsystem(&event_hub);
        watchdog.registerSubsystem(&radio);
        watchdog.registerSubsystem(&star_tracker);
        watchdog.registerSubsystem(&battery);
        watchdog.registerSubsystem(&imu_unit);
    }

    [[nodiscard]] auto verify() -> bool {
        bool ok = true;
        auto check = [&](bool cond, const char* label) -> void {
            if (!cond) {
#if defined(ESP_PLATFORM)
                ESP_LOGE(TOPOLOGY_LOG_TAG, "UNCONNECTED: %s", label);
#else
                (void)std::fprintf(stderr, "[Topology] UNCONNECTED: %s\n", label);
#endif
                ok = false;
            }
        };
        check(radio.command_out.isConnected(), "radio.command_out → cmd_hub");
        check(cmd_hub.ack_out.isConnected(),   "cmd_hub.ack_out → event_hub");
        check(cmd_hub.hasMissionStateSource(), "cmd_hub mission state source");
        check(watchdog.hasBatteryThresholdSources(), "watchdog battery threshold sources");
        check(star_tracker.telemetry_out.isConnected(), "star_tracker.telemetry_out → telem_hub");
        check(battery.telemetry_out.isConnected(), "battery.telemetry_out → telem_hub");
        check(imu_unit.telemetry_out.isConnected(), "imu_unit.telemetry_out → telem_hub");
        check(event_hub.getSourceCount()   >= 2, "event_hub: need >=2 sources");
        check(event_hub.getListenerCount() >= 2, "event_hub: need >=2 listeners");
        if (!ok) {
#if defined(ESP_PLATFORM)
            ESP_LOGE(TOPOLOGY_LOG_TAG, "FATAL: wiring incomplete.");
#else
            (void)std::fprintf(stderr, "[Topology] FATAL: wiring incomplete.\n");
#endif
        }
        return ok;
    }

private:
    OutputPort<CommandPacket> star_tracker_route_{};
    OutputPort<CommandPacket> battery_route_{};
    OutputPort<CommandPacket> imu_unit_route_{};
    InputPort<EventPacket> e_watchdog_{};
    InputPort<EventPacket> e_cmd_hub_{};
    InputPort<EventPacket> e_star_tracker_{};
    InputPort<EventPacket> e_battery_{};
    InputPort<EventPacket> e_imu_unit_{};

    auto wireTelemetry() -> void {
        telem_hub.registerListener(&radio.telem_in);
        telem_hub.registerListener(&recorder.telemetry_in);
        telem_hub.connectInput(star_tracker.telemetry_out);
        telem_hub.connectInput(battery.telemetry_out);
        telem_hub.connectInput(imu_unit.telemetry_out);
    }

    auto wireCommands() -> void {
        radio.command_out.connect(&cmd_hub.cmd_input);
        star_tracker_route_.connect(&star_tracker.cmd_in);
        cmd_hub.registerRoute(100, &star_tracker_route_);
        battery_route_.connect(&battery.cmd_in);
        cmd_hub.registerRoute(200, &battery_route_);
        imu_unit_route_.connect(&imu_unit.cmd_in);
        cmd_hub.registerRoute(300, &imu_unit_route_);
    }

    auto wireEvents() -> void {
        event_hub.registerListener(&radio.event_in);
        event_hub.registerListener(&recorder.event_in);
        watchdog.event_out.connect(&e_watchdog_);
        event_hub.registerEventSource(&e_watchdog_);
        cmd_hub.ack_out.connect(&e_cmd_hub_);
        event_hub.registerEventSource(&e_cmd_hub_);
        star_tracker.event_out.connect(&e_star_tracker_);
        event_hub.registerEventSource(&e_star_tracker_);
        battery.event_out.connect(&e_battery_);
        event_hub.registerEventSource(&e_battery_);
        imu_unit.event_out.connect(&e_imu_unit_);
        event_hub.registerEventSource(&e_imu_unit_);
    }

    auto wireCustom() -> void {
        battery.battery_out_internal.connect(&watchdog.battery_level_in);
        cmd_hub.setMissionStateSource(&watchdog);
        watchdog.setBatteryThresholdSources(&tmr_emergency_battery_pct, &tmr_safe_mode_battery_pct, &tmr_degraded_battery_pct);
    }
};

} // namespace deltav
