#pragma once
// ============================================================================
// TopologyManager.hpp — AUTOGENERATED BY DELTA-V AUTOCODER v4.0
// ============================================================================
// DO NOT EDIT BY HAND.  Regenerate: python3 tools/autocoder.py
// ============================================================================
#include "Port.hpp"
#include "Types.hpp"
#include "RateGroupExecutive.hpp"
#include "TmrStore.hpp"
#include "Hal.hpp"
#include <iostream>
#include "WatchdogComponent.hpp"
#include "TelemHub.hpp"
#include "CommandHub.hpp"
#include "EventHub.hpp"
#include "TelemetryBridge.hpp"
#include "LoggerComponent.hpp"
#include "CommandSequencerComponent.hpp"
#include "FileTransferComponent.hpp"
#include "MemoryDwellComponent.hpp"
#include "TimeSyncComponent.hpp"
#include "PlaybackComponent.hpp"
#include "OtaComponent.hpp"
#include "AtsRtsSequencerComponent.hpp"
#include "LimitCheckerComponent.hpp"
#include "CfdpComponent.hpp"
#include "ModeManagerComponent.hpp"
#include "SensorComponent.hpp"
#include "PowerComponent.hpp"
#include "ImuComponent.hpp"
#include "PayloadMonitorComponent.hpp"

namespace deltav {

struct TopologyManager {
private:
    hal::I2cBus* i2c_{nullptr};

public:
    explicit TopologyManager(hal::I2cBus& i2c) : i2c_(&i2c) {}

    // ── Component instances ───────────────────────────────────────────────
    WatchdogComponent      watchdog        {"Supervisor", 1};
    TelemHub               telem_hub       {"TelemHub", 10};
    CommandHub             cmd_hub         {"CmdHub", 11};
    EventHub               event_hub       {"EventHub", 12};
    TelemetryBridge        radio           {"RadioLink", 20};
    LoggerComponent        recorder        {"BlackBox", 30};
    CommandSequencerComponent cmd_sequencer   {"CmdSequencer", 40};
    FileTransferComponent  file_transfer   {"FileTransfer", 41};
    MemoryDwellComponent   memory_dwell    {"MemoryDwell", 42};
    TimeSyncComponent      time_sync       {"TimeSync", 43};
    PlaybackComponent      playback        {"Playback", 44};
    OtaComponent           ota_manager     {"OtaManager", 45};
    AtsRtsSequencerComponent ats_rts         {"AtsRtsSequencer", 46};
    LimitCheckerComponent  limit_checker   {"LimitChecker", 47};
    CfdpComponent          cfdp_manager    {"CfdpManager", 48};
    ModeManagerComponent   mode_manager    {"ModeManager", 49};
    SensorComponent        star_tracker    {"StarTracker", 100};
    PowerComponent         battery         {"BatterySystem", 200};
    ImuComponent           imu_unit        {"IMU_01", 300, *i2c_};
    PayloadMonitorComponent payload_monitor {"PayloadMonitor", 400};

    // TMR-protected parameters (auto-generated)
    TmrStore<float>  tmr_safe_mode_battery_pct{ 5.0f };
    TmrStore<float>  tmr_degraded_battery_pct{ 15.0f };
    TmrStore<float>  tmr_emergency_battery_pct{ 2.0f };

    // ── Lifecycle ─────────────────────────────────────────────────────────

    auto wire() -> void {
        wireTelemetry();
        wireCommands();
        wireEvents();
        wireCustom();
        std::cout << "[Topology] All ports connected.\n";
    }

    auto registerAll(RateGroupExecutive& rge) -> void {
        // ── FAST tier (10 Hz) ─────────────────────────
        rge.registerFast(&star_tracker);
        rge.registerFast(&imu_unit);
        // ── NORM tier  (1 Hz) ─────────────────────────
        rge.registerNorm(&watchdog);
        rge.registerNorm(&telem_hub);
        rge.registerNorm(&cmd_hub);
        rge.registerNorm(&event_hub);
        rge.registerNorm(&recorder);
        rge.registerNorm(&cmd_sequencer);
        rge.registerNorm(&file_transfer);
        rge.registerNorm(&memory_dwell);
        rge.registerNorm(&time_sync);
        rge.registerNorm(&playback);
        rge.registerNorm(&ota_manager);
        rge.registerNorm(&ats_rts);
        rge.registerNorm(&limit_checker);
        rge.registerNorm(&cfdp_manager);
        rge.registerNorm(&mode_manager);
        rge.registerNorm(&battery);
        rge.registerNorm(&payload_monitor);
        // ── Active (own thread) ────────────────────────
        rge.registerComponent(&radio);

    }

    auto registerFdir() -> void {
        watchdog.registerSubsystem(&watchdog);
        watchdog.registerSubsystem(&cmd_hub);
        watchdog.registerSubsystem(&event_hub);
        watchdog.registerSubsystem(&radio);
        watchdog.registerSubsystem(&cmd_sequencer);
        watchdog.registerSubsystem(&file_transfer);
        watchdog.registerSubsystem(&memory_dwell);
        watchdog.registerSubsystem(&time_sync);
        watchdog.registerSubsystem(&playback);
        watchdog.registerSubsystem(&ota_manager);
        watchdog.registerSubsystem(&ats_rts);
        watchdog.registerSubsystem(&limit_checker);
        watchdog.registerSubsystem(&cfdp_manager);
        watchdog.registerSubsystem(&mode_manager);
        watchdog.registerSubsystem(&star_tracker);
        watchdog.registerSubsystem(&battery);
        watchdog.registerSubsystem(&imu_unit);
        watchdog.registerSubsystem(&payload_monitor);
    }

    [[nodiscard]] auto verify() -> bool {
        bool ok = true;
        auto check = [&](bool cond, const char* label) -> void {
            if (!cond) {
                std::cerr << "[Topology] UNCONNECTED: " << label << "\n";
                ok = false;
            }
        };
        check(radio.command_out.isConnectedTo(&cmd_hub.cmd_input), "radio.command_out → cmd_hub");
        check(telem_hub.getInputCount() >= 14, "telem_hub: expected >=14 inputs");
        check(telem_hub.getListenerCount() >= 3, "telem_hub: need >=3 listeners");
        check(cmd_hub.routeCount() >= 14, "cmd_hub: expected >=14 routes");
        check(cmd_hub.hasMissionStateSource(), "cmd_hub mission state source");
        check(watchdog.hasBatteryThresholdSources(), "watchdog battery threshold sources");
        check(telem_hub.isInputConnected(0, cmd_sequencer.telemetry_out), "cmd_sequencer.telemetry_out → telem_hub");
        check(telem_hub.isInputConnected(1, file_transfer.telemetry_out), "file_transfer.telemetry_out → telem_hub");
        check(telem_hub.isInputConnected(2, memory_dwell.telemetry_out), "memory_dwell.telemetry_out → telem_hub");
        check(telem_hub.isInputConnected(3, time_sync.telemetry_out), "time_sync.telemetry_out → telem_hub");
        check(telem_hub.isInputConnected(4, playback.telemetry_out), "playback.telemetry_out → telem_hub");
        check(telem_hub.isInputConnected(5, ota_manager.telemetry_out), "ota_manager.telemetry_out → telem_hub");
        check(telem_hub.isInputConnected(6, ats_rts.telemetry_out), "ats_rts.telemetry_out → telem_hub");
        check(telem_hub.isInputConnected(7, limit_checker.telemetry_out), "limit_checker.telemetry_out → telem_hub");
        check(telem_hub.isInputConnected(8, cfdp_manager.telemetry_out), "cfdp_manager.telemetry_out → telem_hub");
        check(telem_hub.isInputConnected(9, mode_manager.telemetry_out), "mode_manager.telemetry_out → telem_hub");
        check(telem_hub.isInputConnected(10, star_tracker.telemetry_out), "star_tracker.telemetry_out → telem_hub");
        check(telem_hub.isInputConnected(11, battery.telemetry_out), "battery.telemetry_out → telem_hub");
        check(telem_hub.isInputConnected(12, imu_unit.telemetry_out), "imu_unit.telemetry_out → telem_hub");
        check(telem_hub.isInputConnected(13, payload_monitor.telemetry_out), "payload_monitor.telemetry_out → telem_hub");
        check(cmd_sequencer_route_.isConnectedTo(&cmd_sequencer.cmd_in), "cmd_sequencer_route_ → cmd_sequencer.cmd_in");
        check(file_transfer_route_.isConnectedTo(&file_transfer.cmd_in), "file_transfer_route_ → file_transfer.cmd_in");
        check(memory_dwell_route_.isConnectedTo(&memory_dwell.cmd_in), "memory_dwell_route_ → memory_dwell.cmd_in");
        check(time_sync_route_.isConnectedTo(&time_sync.cmd_in), "time_sync_route_ → time_sync.cmd_in");
        check(playback_route_.isConnectedTo(&playback.cmd_in), "playback_route_ → playback.cmd_in");
        check(ota_manager_route_.isConnectedTo(&ota_manager.cmd_in), "ota_manager_route_ → ota_manager.cmd_in");
        check(ats_rts_route_.isConnectedTo(&ats_rts.cmd_in), "ats_rts_route_ → ats_rts.cmd_in");
        check(limit_checker_route_.isConnectedTo(&limit_checker.cmd_in), "limit_checker_route_ → limit_checker.cmd_in");
        check(cfdp_manager_route_.isConnectedTo(&cfdp_manager.cmd_in), "cfdp_manager_route_ → cfdp_manager.cmd_in");
        check(mode_manager_route_.isConnectedTo(&mode_manager.cmd_in), "mode_manager_route_ → mode_manager.cmd_in");
        check(star_tracker_route_.isConnectedTo(&star_tracker.cmd_in), "star_tracker_route_ → star_tracker.cmd_in");
        check(battery_route_.isConnectedTo(&battery.cmd_in), "battery_route_ → battery.cmd_in");
        check(imu_unit_route_.isConnectedTo(&imu_unit.cmd_in), "imu_unit_route_ → imu_unit.cmd_in");
        check(payload_monitor_route_.isConnectedTo(&payload_monitor.cmd_in), "payload_monitor_route_ → payload_monitor.cmd_in");
        check(watchdog.event_out.isConnectedTo(&e_watchdog_), "watchdog.event_out → event_hub");
        check(cmd_hub.ack_out.isConnectedTo(&e_cmd_hub_), "cmd_hub.ack_out → event_hub");
        check(cmd_sequencer.event_out.isConnectedTo(&e_cmd_sequencer_), "cmd_sequencer.event_out → event_hub");
        check(file_transfer.event_out.isConnectedTo(&e_file_transfer_), "file_transfer.event_out → event_hub");
        check(memory_dwell.event_out.isConnectedTo(&e_memory_dwell_), "memory_dwell.event_out → event_hub");
        check(time_sync.event_out.isConnectedTo(&e_time_sync_), "time_sync.event_out → event_hub");
        check(playback.event_out.isConnectedTo(&e_playback_), "playback.event_out → event_hub");
        check(ota_manager.event_out.isConnectedTo(&e_ota_manager_), "ota_manager.event_out → event_hub");
        check(ats_rts.event_out.isConnectedTo(&e_ats_rts_), "ats_rts.event_out → event_hub");
        check(limit_checker.event_out.isConnectedTo(&e_limit_checker_), "limit_checker.event_out → event_hub");
        check(cfdp_manager.event_out.isConnectedTo(&e_cfdp_manager_), "cfdp_manager.event_out → event_hub");
        check(mode_manager.event_out.isConnectedTo(&e_mode_manager_), "mode_manager.event_out → event_hub");
        check(star_tracker.event_out.isConnectedTo(&e_star_tracker_), "star_tracker.event_out → event_hub");
        check(battery.event_out.isConnectedTo(&e_battery_), "battery.event_out → event_hub");
        check(imu_unit.event_out.isConnectedTo(&e_imu_unit_), "imu_unit.event_out → event_hub");
        check(payload_monitor.event_out.isConnectedTo(&e_payload_monitor_), "payload_monitor.event_out → event_hub");
        check(event_hub.getSourceCount()   >= 16, "event_hub: expected event sources");
        check(event_hub.getListenerCount() >= 3, "event_hub: need >=3 listeners");
        if (!ok) std::cerr << "[Topology] FATAL: wiring incomplete.\n";
        return ok;
    }

private:
    OutputPort<CommandPacket> cmd_sequencer_route_{};
    OutputPort<CommandPacket> file_transfer_route_{};
    OutputPort<CommandPacket> memory_dwell_route_{};
    OutputPort<CommandPacket> time_sync_route_{};
    OutputPort<CommandPacket> playback_route_{};
    OutputPort<CommandPacket> ota_manager_route_{};
    OutputPort<CommandPacket> ats_rts_route_{};
    OutputPort<CommandPacket> limit_checker_route_{};
    OutputPort<CommandPacket> cfdp_manager_route_{};
    OutputPort<CommandPacket> mode_manager_route_{};
    OutputPort<CommandPacket> star_tracker_route_{};
    OutputPort<CommandPacket> battery_route_{};
    OutputPort<CommandPacket> imu_unit_route_{};
    OutputPort<CommandPacket> payload_monitor_route_{};
    InputPort<EventPacket> e_watchdog_{};
    InputPort<EventPacket> e_cmd_hub_{};
    InputPort<EventPacket> e_cmd_sequencer_{};
    InputPort<EventPacket> e_file_transfer_{};
    InputPort<EventPacket> e_memory_dwell_{};
    InputPort<EventPacket> e_time_sync_{};
    InputPort<EventPacket> e_playback_{};
    InputPort<EventPacket> e_ota_manager_{};
    InputPort<EventPacket> e_ats_rts_{};
    InputPort<EventPacket> e_limit_checker_{};
    InputPort<EventPacket> e_cfdp_manager_{};
    InputPort<EventPacket> e_mode_manager_{};
    InputPort<EventPacket> e_star_tracker_{};
    InputPort<EventPacket> e_battery_{};
    InputPort<EventPacket> e_imu_unit_{};
    InputPort<EventPacket> e_payload_monitor_{};

    auto wireTelemetry() -> void {
        telem_hub.registerListener(&radio.telem_in);
        telem_hub.registerListener(&recorder.telemetry_in);
        telem_hub.connectInput(cmd_sequencer.telemetry_out);
        telem_hub.connectInput(file_transfer.telemetry_out);
        telem_hub.connectInput(memory_dwell.telemetry_out);
        telem_hub.connectInput(time_sync.telemetry_out);
        telem_hub.connectInput(playback.telemetry_out);
        telem_hub.connectInput(ota_manager.telemetry_out);
        telem_hub.connectInput(ats_rts.telemetry_out);
        telem_hub.connectInput(limit_checker.telemetry_out);
        telem_hub.connectInput(cfdp_manager.telemetry_out);
        telem_hub.connectInput(mode_manager.telemetry_out);
        telem_hub.connectInput(star_tracker.telemetry_out);
        telem_hub.connectInput(battery.telemetry_out);
        telem_hub.connectInput(imu_unit.telemetry_out);
        telem_hub.connectInput(payload_monitor.telemetry_out);
    }

    auto wireCommands() -> void {
        cmd_hub.registerCommandPolicy(200, 1, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(200, 2, OpClass::OPERATIONAL);
        cmd_hub.registerCommandPolicy(100, 1, OpClass::OPERATIONAL);
        cmd_hub.registerCommandPolicy(300, 1, OpClass::OPERATIONAL);
        cmd_hub.registerCommandPolicy(400, 1, OpClass::OPERATIONAL);
        cmd_hub.registerCommandPolicy(400, 2, OpClass::RESTRICTED);
        cmd_hub.registerCommandPolicy(400, 3, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(40, 1, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(40, 2, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(40, 3, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(40, 4, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(40, 5, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(41, 1, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(41, 2, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(41, 3, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(41, 4, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(42, 1, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(42, 2, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(42, 3, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(42, 10, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(42, 11, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(42, 12, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(42, 13, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(42, 14, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(42, 15, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(43, 1, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(43, 2, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(43, 3, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(43, 4, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(43, 5, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(43, 6, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(44, 1, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(44, 2, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(44, 3, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(44, 4, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(44, 5, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(44, 6, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(45, 1, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(45, 2, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(45, 3, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(45, 4, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(45, 5, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(45, 6, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(45, 7, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(46, 1, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(46, 2, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(46, 3, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(46, 4, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(46, 5, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(46, 6, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(46, 7, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(46, 8, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(46, 9, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(46, 10, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(46, 11, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(47, 1, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(47, 2, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(47, 3, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(47, 4, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(47, 5, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(47, 6, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(47, 7, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(47, 8, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(47, 9, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(48, 1, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(48, 2, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(48, 3, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(48, 4, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(48, 5, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(48, 6, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(48, 7, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(48, 8, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(49, 1, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(49, 2, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(49, 3, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(49, 4, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(49, 5, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(49, 6, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(49, 7, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(49, 8, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(49, 9, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(49, 10, OpClass::HOUSEKEEPING);
        cmd_hub.registerCommandPolicy(49, 11, OpClass::HOUSEKEEPING);
        radio.command_out.connect(&cmd_hub.cmd_input);
        cmd_sequencer_route_.connect(&cmd_sequencer.cmd_in);
        cmd_hub.registerRoute(40, &cmd_sequencer_route_);
        file_transfer_route_.connect(&file_transfer.cmd_in);
        cmd_hub.registerRoute(41, &file_transfer_route_);
        memory_dwell_route_.connect(&memory_dwell.cmd_in);
        cmd_hub.registerRoute(42, &memory_dwell_route_);
        time_sync_route_.connect(&time_sync.cmd_in);
        cmd_hub.registerRoute(43, &time_sync_route_);
        playback_route_.connect(&playback.cmd_in);
        cmd_hub.registerRoute(44, &playback_route_);
        ota_manager_route_.connect(&ota_manager.cmd_in);
        cmd_hub.registerRoute(45, &ota_manager_route_);
        ats_rts_route_.connect(&ats_rts.cmd_in);
        cmd_hub.registerRoute(46, &ats_rts_route_);
        limit_checker_route_.connect(&limit_checker.cmd_in);
        cmd_hub.registerRoute(47, &limit_checker_route_);
        cfdp_manager_route_.connect(&cfdp_manager.cmd_in);
        cmd_hub.registerRoute(48, &cfdp_manager_route_);
        mode_manager_route_.connect(&mode_manager.cmd_in);
        cmd_hub.registerRoute(49, &mode_manager_route_);
        star_tracker_route_.connect(&star_tracker.cmd_in);
        cmd_hub.registerRoute(100, &star_tracker_route_);
        battery_route_.connect(&battery.cmd_in);
        cmd_hub.registerRoute(200, &battery_route_);
        imu_unit_route_.connect(&imu_unit.cmd_in);
        cmd_hub.registerRoute(300, &imu_unit_route_);
        payload_monitor_route_.connect(&payload_monitor.cmd_in);
        cmd_hub.registerRoute(400, &payload_monitor_route_);
    }

    auto wireEvents() -> void {
        event_hub.registerListener(&radio.event_in);
        event_hub.registerListener(&recorder.event_in);
        watchdog.event_out.connect(&e_watchdog_);
        event_hub.registerEventSource(&e_watchdog_);
        cmd_hub.ack_out.connect(&e_cmd_hub_);
        event_hub.registerEventSource(&e_cmd_hub_);
        cmd_sequencer.event_out.connect(&e_cmd_sequencer_);
        event_hub.registerEventSource(&e_cmd_sequencer_);
        file_transfer.event_out.connect(&e_file_transfer_);
        event_hub.registerEventSource(&e_file_transfer_);
        memory_dwell.event_out.connect(&e_memory_dwell_);
        event_hub.registerEventSource(&e_memory_dwell_);
        time_sync.event_out.connect(&e_time_sync_);
        event_hub.registerEventSource(&e_time_sync_);
        playback.event_out.connect(&e_playback_);
        event_hub.registerEventSource(&e_playback_);
        ota_manager.event_out.connect(&e_ota_manager_);
        event_hub.registerEventSource(&e_ota_manager_);
        ats_rts.event_out.connect(&e_ats_rts_);
        event_hub.registerEventSource(&e_ats_rts_);
        limit_checker.event_out.connect(&e_limit_checker_);
        event_hub.registerEventSource(&e_limit_checker_);
        cfdp_manager.event_out.connect(&e_cfdp_manager_);
        event_hub.registerEventSource(&e_cfdp_manager_);
        mode_manager.event_out.connect(&e_mode_manager_);
        event_hub.registerEventSource(&e_mode_manager_);
        star_tracker.event_out.connect(&e_star_tracker_);
        event_hub.registerEventSource(&e_star_tracker_);
        battery.event_out.connect(&e_battery_);
        event_hub.registerEventSource(&e_battery_);
        imu_unit.event_out.connect(&e_imu_unit_);
        event_hub.registerEventSource(&e_imu_unit_);
        payload_monitor.event_out.connect(&e_payload_monitor_);
        event_hub.registerEventSource(&e_payload_monitor_);
    }

    auto wireCustom() -> void {
        battery.battery_out_internal.connect(&watchdog.battery_level_in);
        cmd_hub.setMissionStateSource(&watchdog);
        watchdog.setBatteryThresholdSources(&tmr_emergency_battery_pct, &tmr_safe_mode_battery_pct, &tmr_degraded_battery_pct);
        cmd_sequencer.command_out.connect(&cmd_hub.cmd_input);
        ats_rts.command_out.connect(&cmd_hub.cmd_input);
        mode_manager.command_out.connect(&cmd_hub.cmd_input);
        event_hub.registerListener(&ats_rts.event_in);
        telem_hub.registerListener(&limit_checker.telem_in);
    }
};

} // namespace deltav
