#pragma once
#include <cstdint>
#include <cstring>

namespace deltav {

// NASA-GRADE: Enforce strict DO-178C memory layout (Zero compiler padding allowed)
// -----------------------------------------------------------------
// ⚠️ AUTOGENERATED FILE: DO NOT MODIFY BY HAND. RUN autocoder.py ⚠️
// -----------------------------------------------------------------
#pragma pack(push, 1)

// 🚀 UPGRADE: Aerospace Packet Framing Header (10 Bytes)
struct CcsdsHeader {
    uint32_t sync_word;
    uint16_t apid;
    uint16_t seq_count;
    uint16_t payload_len;
};

struct TelemetryPacket {
    uint32_t timestamp_ms;
    uint32_t component_id;
    float data_payload;
};

struct CommandPacket {
    uint32_t target_id;
    uint32_t opcode;
    float argument;
};

struct EventPacket {
    uint32_t severity;
    char message[32];

    static EventPacket create(uint32_t sev, const char* msg) {
        EventPacket p;
        p.severity = sev;
        std::strncpy(p.message, msg, 31);
        p.message[31] = '\0';
        return p;
    }
};

#pragma pack(pop)

} // namespace deltav
