#pragma once
// =============================================================================
// Types.hpp — DELTA-V Wire Protocol & Packet Definitions
// =============================================================================
// ⚠️  AUTOGENERATED FILE: DO NOT MODIFY BY HAND. RUN autocoder.py  ⚠️
//
// DO-178C: #pragma pack(push,1) enforces zero compiler padding.
// All sizeof() assertions are proven in Serializer.hpp at compile time.
//
// CCSDS compliance note:
//   - Sync word 0x1ACFFC1D is the standard CCSDS transfer frame sync marker.
//   - APID 10 = Telemetry, APID 20 = Events, APID 30 = Commands (mission-local).
//   - CRC-16/CCITT appended to every downlink frame (computed in TelemetryBridge).
// =============================================================================
#include <cstdint>
#include <cstring>

namespace deltav {

#pragma pack(push, 1)

// ---------------------------------------------------------------------------
// CCSDS Transfer Frame Header (10 bytes)
// Sync word changed from 0xDEADBEEF (non-standard) to 0x1ACFFC1D (CCSDS std).
// ---------------------------------------------------------------------------
struct CcsdsHeader {
    uint32_t sync_word;   // 0x1ACFFC1D — CCSDS standard sync marker
    uint16_t apid;        // Application Process ID
    uint16_t seq_count;   // Uplink/downlink sequence counter
    uint16_t payload_len; // Payload byte length (excludes header and CRC)
};
static_assert(sizeof(CcsdsHeader) == 10, "CcsdsHeader must be 10 bytes");

// CRC appended after payload on all downlink frames (2 bytes)
struct CcsdsCrc {
    uint16_t crc16;
};

// ---------------------------------------------------------------------------
// Application Packets
// ---------------------------------------------------------------------------
struct TelemetryPacket {
    uint32_t timestamp_ms;  // Mission Elapsed Time from TimeService::getMET()
    uint32_t component_id;  // Matches Component::getId()
    float    data_payload;  // Engineering-unit value
};
static_assert(sizeof(TelemetryPacket) == 12, "TelemetryPacket must be 12 bytes");

struct CommandPacket {
    uint32_t target_id;   // Destination component ID (routes through CommandHub)
    uint32_t opcode;      // Mission-defined operation code
    float    argument;    // Optional scalar argument
};
static_assert(sizeof(CommandPacket) == 12, "CommandPacket must be 12 bytes");

struct EventPacket {
    uint32_t severity;    // 1=INFO, 2=WARNING, 3=CRITICAL
    uint32_t source_id;   // Component ID that raised the event
    char     message[28]; // Null-terminated ASCII message

    static EventPacket create(uint32_t sev, uint32_t src, const char* msg) {
        EventPacket p{};
        p.severity  = sev;
        p.source_id = src;
        std::strncpy(p.message, msg, sizeof(p.message) - 1);
        p.message[sizeof(p.message) - 1] = '\0';
        return p;
    }
};
static_assert(sizeof(EventPacket) == 36, "EventPacket must be 36 bytes");

#pragma pack(pop)

// Severity constants — use these instead of magic numbers
namespace Severity {
    constexpr uint32_t INFO     = 1;
    constexpr uint32_t WARNING  = 2;
    constexpr uint32_t CRITICAL = 3;
}

// APID constants
namespace Apid {
    constexpr uint16_t TELEMETRY = 10;
    constexpr uint16_t EVENT     = 20;
    constexpr uint16_t COMMAND   = 30;
}

// CCSDS standard sync word
constexpr uint32_t CCSDS_SYNC_WORD = 0x1ACFFC1Du;

} // namespace deltav