#pragma once
// =============================================================================
// Types.hpp — DELTA-V Wire Protocol & Packet Definitions
// =============================================================================
// ⚠️  AUTOGENERATED FILE: DO NOT MODIFY BY HAND. RUN autocoder.py  ⚠️

#include <cstdint>
#include <cstring>

namespace deltav {

#pragma pack(push, 1)

struct CcsdsHeader {
    uint32_t sync_word;    
    uint16_t apid;         
    uint16_t seq_count;    
    uint16_t payload_len;  
};
static_assert(sizeof(CcsdsHeader) == 10, "CcsdsHeader must be 10 bytes");

struct CcsdsCrc {
    uint16_t crc16;        
};

struct TelemetryPacket {
    uint32_t timestamp_ms;   
    uint32_t component_id;   
    float    data_payload;   
};
static_assert(sizeof(TelemetryPacket) == 12, "TelemetryPacket must be 12 bytes");

struct CommandPacket {
    uint32_t target_id;    
    uint32_t opcode;       
    float    argument;     
};
static_assert(sizeof(CommandPacket) == 12, "CommandPacket must be 12 bytes");

struct EventPacket {
    uint32_t severity;     
    uint32_t source_id;    
    char     message[28];  

    static EventPacket create(uint32_t sev, uint32_t src, const char* msg) {
        EventPacket p{};
        p.severity  = sev;
        p.source_id = src;
        std::strncpy(p.message, msg, sizeof(p.message) - 1);
        p.message[sizeof(p.message) - 1] = '\0';
        return p;
    }
};
static_assert(sizeof(EventPacket) == 36, "EventPacket must be 36 bytes");

#pragma pack(pop)

namespace Severity {
    constexpr uint32_t INFO     = 1;
    constexpr uint32_t WARNING  = 2;
    constexpr uint32_t CRITICAL = 3;
}

namespace Apid {
    constexpr uint16_t TELEMETRY = 10;
    constexpr uint16_t EVENT     = 20;
    constexpr uint16_t COMMAND   = 30;
}

constexpr uint32_t CCSDS_SYNC_WORD = 0x1ACFFC1Du;

} // namespace deltav
